#!/usr/bin/env node
/**
 * One-time fetch of the two Google families the app loads through
 * `next/font/google` (Inter, Source Serif 4).
 *
 * `next/font` self-hosts at build time; nothing in the repo carries the font
 * binaries, so a bundle built from src/ alone renders every design in a
 * fallback face. This mirrors what next/font does — downloads the same latin
 * woff2 files and writes an @font-face sheet — into .design-sync/fonts/, which
 * is committed so re-syncs need no network and stay byte-reproducible.
 *
 * Re-run only to change families, weights, or subsets.
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const OUT = resolve(dirname(fileURLToPath(import.meta.url)), "fonts");
const UA =
  "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36";

/** Mirrors the next/font calls in src/app/layout.tsx. */
const FAMILIES = [
  { css: "Inter:wght@100..900", family: "Inter", varName: "--font-body" },
  { css: "Source+Serif+4:wght@600;700", family: "Source Serif 4", varName: "--font-display" },
];
const SUBSET = "latin"; // subsets: ["latin"] in layout.tsx

mkdirSync(OUT, { recursive: true });

const url = `https://fonts.googleapis.com/css2?${FAMILIES.map((f) => `family=${f.css}`).join(
  "&",
)}&display=swap`;
const sheet = await (await fetch(url, { headers: { "User-Agent": UA } })).text();

// Google's sheet emits one commented subset group per @font-face block.
const blocks = sheet
  .split(/\/\*\s*([\w-\[\]]+)\s*\*\//)
  .slice(1)
  .reduce((acc, part, i, arr) => (i % 2 ? acc : [...acc, { subset: part, css: arr[i + 1] }]), []);

const out = [
  "/* Generated by .design-sync/fetch-fonts.mjs — the families src/app/layout.tsx",
  "   loads via next/font/google, self-hosted the same way next/font does.",
  "   Edit fetch-fonts.mjs and re-run rather than editing this file. */",
  "",
];

for (const { subset, css } of blocks) {
  if (subset !== SUBSET) continue;
  const family = /font-family:\s*'([^']+)'/.exec(css)?.[1];
  const weight = /font-weight:\s*([^;]+);/.exec(css)?.[1].trim();
  const style = /font-style:\s*([^;]+);/.exec(css)?.[1].trim() ?? "normal";
  const src = /src:\s*url\(([^)]+)\)/.exec(css)?.[1];
  if (!family || !src) continue;

  const slug = `${family.toLowerCase().replace(/\s+/g, "-")}-${weight.replace(/\s+/g, "")}-${style}`;
  const file = `${slug}.woff2`;
  const bytes = Buffer.from(await (await fetch(src)).arrayBuffer());
  writeFileSync(resolve(OUT, file), bytes);
  console.log(`[font] ${file} — ${(bytes.length / 1024).toFixed(1)} KB`);

  const range = /unicode-range:\s*([^;]+);/.exec(css)?.[1].trim();
  out.push(
    `@font-face {`,
    `  font-family: '${family}';`,
    `  font-style: ${style};`,
    `  font-weight: ${weight};`,
    `  font-display: swap;`,
    `  src: url('./${file}') format('woff2');`,
    ...(range ? [`  unicode-range: ${range};`] : []),
    `}`,
    ``,
  );
}

// next/font exposes each family through a CSS variable set on <html>; the
// design system's stylesheet reads those, so bind them at :root here.
out.push(
  "/* next/font sets these on <html> via the `variable` option; the design",
  "   system's own stylesheet resolves --font-sans/--font-display through them. */",
  ":root {",
  ...FAMILIES.map((f) => `  ${f.varName}: '${f.family}';`),
  "}",
  "",
);

writeFileSync(resolve(OUT, "fonts.css"), out.join("\n"));
console.log(`[font] wrote ${resolve(OUT, "fonts.css")}`);
