#!/usr/bin/env node
/**
 * Everything that must exist before the design-sync converter runs.
 * Recorded as `buildCmd` in config.json — re-run it whenever src/ changes.
 *
 *   1. Tailwind → static CSS. The utility classes the components reference
 *      are generated at `next build`; without this the bundle ships tokens
 *      but no utilities, and every card renders unstyled.
 *   2. tsc → a .d.ts tree under dist/types. This app has no build output, so
 *      the converter would otherwise fall back to a content scan and emit
 *      `[key: string]: unknown` for all 36 components. That empty contract is
 *      what the Claude Design agent codes against, so it must be real:
 *      findTypesRoot() picks up dist/types with no package.json change.
 */
import { execFileSync } from "node:child_process";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "..");
const run = (cmd, args) => execFileSync(cmd, args, { cwd: repo, stdio: "inherit" });

run(process.execPath, [resolve(here, "build-css.mjs")]);

run(process.execPath, [
  resolve(repo, "node_modules/typescript/bin/tsc"),
  "-p",
  resolve(here, "tsconfig.types.json"),
]);
console.log("[types] dist/types refreshed");

/**
 * Barrel entry for the emitted declarations.
 *
 * The converter derives each component's prop contract from the call
 * signature it finds in the module `package.json#types` points at. Without
 * this barrel it finds nothing and every component emits an empty
 * `[key: string]: unknown` body — the app builds and renders fine, so the
 * loss is invisible until the design agent has no idea what props exist.
 */
import { readdirSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const typesDir = resolve(repo, "dist/types");
const walk = (dir) =>
  readdirSync(dir, { withFileTypes: true }).flatMap((e) =>
    e.isDirectory() ? walk(join(dir, e.name)) : e.name.endsWith(".d.ts") ? [join(dir, e.name)] : [],
  );

const modules = walk(join(typesDir, "components"))
  .map((f) => "./" + relative(typesDir, f).replace(/\.d\.ts$/, ""))
  .sort();

writeFileSync(
  join(typesDir, "index.d.ts"),
  [
    "// Generated by .design-sync/prepare.mjs — do not edit.",
    "// Entry point for design-sync's prop extraction (package.json#types).",
    "",
    ...modules.map((m) => `export * from ${JSON.stringify(m)};`),
    "",
  ].join("\n"),
);
console.log(`[types] index.d.ts barrel — ${modules.length} modules`);

/**
 * Rewrite `@/…` specifiers in the emitted declarations to relative paths.
 *
 * tsc preserves the path alias verbatim, but the converter parses these files
 * with a bare ts-morph project that has no `paths` map — so `@/data/network`
 * resolves to nothing, `StatusPill.status` degrades to `any`, and
 * `RouteCard.route: Route` names a type the emitted .d.ts never imports.
 */
import { readFileSync } from "node:fs";

for (const file of walk(typesDir)) {
  const before = readFileSync(file, "utf8");
  const after = before.replace(/(\bfrom\s*")@\/([^"]+)(")/g, (_m, pre, target, post) => {
    let rel = relative(dirname(file), join(typesDir, target)).split("\\").join("/");
    if (!rel.startsWith(".")) rel = `./${rel}`;
    return pre + rel + post;
  });
  if (after !== before) writeFileSync(file, after);
}
console.log("[types] rewrote @/ specifiers to relative paths");
